// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: extension/extension.proto

package extension

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type HttpRestOption struct {
	// 路由前缀
	Preffix              string   `protobuf:"bytes,1,opt,name=preffix,proto3" json:"preffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpRestOption) Reset()         { *m = HttpRestOption{} }
func (m *HttpRestOption) String() string { return proto.CompactTextString(m) }
func (*HttpRestOption) ProtoMessage()    {}
func (*HttpRestOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f66318087fa9fbb, []int{0}
}
func (m *HttpRestOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRestOption.Unmarshal(m, b)
}
func (m *HttpRestOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRestOption.Marshal(b, m, deterministic)
}
func (m *HttpRestOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRestOption.Merge(m, src)
}
func (m *HttpRestOption) XXX_Size() int {
	return xxx_messageInfo_HttpRestOption.Size(m)
}
func (m *HttpRestOption) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRestOption.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRestOption proto.InternalMessageInfo

func (m *HttpRestOption) GetPreffix() string {
	if m != nil {
		return m.Preffix
	}
	return ""
}

var E_Rest = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*HttpRestOption)(nil),
	Field:         20200229,
	Name:          "extension.rest",
	Tag:           "bytes,20200229,opt,name=rest",
	Filename:      "extension/extension.proto",
}

func init() {
	proto.RegisterType((*HttpRestOption)(nil), "extension.HttpRestOption")
	proto.RegisterExtension(E_Rest)
}

func init() { proto.RegisterFile("extension/extension.proto", fileDescriptor_5f66318087fa9fbb) }

var fileDescriptor_5f66318087fa9fbb = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xad, 0x28, 0x49,
	0xcd, 0x2b, 0xce, 0xcc, 0xcf, 0xd3, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x52, 0x0a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0x10, 0x89, 0xa4, 0xd2, 0x34, 0xfd,
	0x94, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0xfc, 0x22, 0x88, 0x98, 0x92, 0x16, 0x17, 0x9f,
	0x47, 0x49, 0x49, 0x41, 0x50, 0x6a, 0x71, 0x89, 0x7f, 0x41, 0x49, 0x66, 0x7e, 0x9e, 0x90, 0x04,
	0x17, 0x7b, 0x41, 0x51, 0x6a, 0x5a, 0x5a, 0x66, 0x85, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x8c, 0x6b, 0x15, 0xc8, 0xc5, 0x52, 0x94, 0x5a, 0x5c, 0x22, 0x24, 0xaf, 0x87, 0x66, 0xac, 0x5e,
	0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0x2a, 0xc4, 0x84, 0x62, 0x89, 0xa5, 0xdf, 0x2e, 0x70, 0x2a,
	0x30, 0x6a, 0x70, 0x1b, 0x49, 0xea, 0x21, 0x1c, 0x87, 0x6a, 0x4d, 0x10, 0xd8, 0x28, 0x27, 0xa5,
	0x28, 0x85, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0x92, 0xf4, 0xa2,
	0x82, 0x64, 0xfd, 0x3c, 0x30, 0x09, 0xd7, 0x98, 0xc4, 0x06, 0xb6, 0xc6, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xcc, 0x50, 0x4c, 0x13, 0xf3, 0x00, 0x00, 0x00,
}
