log_level = "debug"
[service]
[service.Greeter]
# address = "localhost:50051"
address = "localhost:2080"
# reuse_desc = true
proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
include_imports = "helloworld/greeter.proto"
keepalive = "100s"
datas = ["1","2","3"]
# datas = ['["1","2","3"]']

[service.Language]
address = "localhost:2080"
# reuse_desc = true
proto_base_path = "$GOPATH/src/github.com/tgrpc/ngrpc"
include_imports = "helloworld/lang.proto"
keepalive = "100s"

[[invokes]]
service= "Greeter"
method = "helloworld.Greeter/SayHello"
headers = ["customerId:123", "region:UK"]
data = '{"name":"@$this"}'
n = 1

[[invokes]]
service= "Language"
method = "helloworld.LangService/List"
headers = ["customerId:123", "region:UK"]
data = '{}'
# n = 1
